/* eslint-disable react/prop-types */
import { useEffect, useMemo, useState } from 'react'
import './App.css'
import './overrides.css'
import './audio-overrides.css'
import './ui-overrides.css'
import './win95-polish.css'
import './media-preview.css'
import './minesweeper.css'
import './mobile.css'
import './mobile-portfolio.css'
import './desktop-feed.css'
import folderIcon from './assets/folder.png'
import mediaIcon from './assets/display.png'
import bioIcon from './assets/notepad.png'
import winampIcon from './assets/winampIcon.png'

const wallpaperFiles = import.meta.glob('./assets/wallpapers/*.{jpg,jpeg,png,gif,webp}', { eager: true, query: '?url', import: 'default' })
const wallpapers = Object.entries(wallpaperFiles).sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true })).map(([, url]) => url)
const appIcons = { director: folderIcon, composer: winampIcon, media: mediaIcon }
const windowGifs = { director: '/gif/theatre.gif', composer: '/gif/winamp.gif', media: '/gif/lab.gif' }
const githubLinks = { 'infinite pong ambient': 'https://github.com/KarimV705/pong', paparazzi: 'https://github.com/KarimV705/paparazzi.toe', 'ZMQ_BRIDGE': 'https://github.com/KarimV705/zmq_plugin', 'Binance to CV': 'https://github.com/KarimV705/BinanceToCv', 'realtime image digital burn': 'https://github.com/KarimV705/digital-burn' }
const demoGifs = { 'DnA / DnB': '/demos/dnb.gif', 'alphafold sonarisation': '/demos/alphafold.gif', 'infinite pong ambient': '/demos/pong.gif', 'realtime image digital burn': '/demos/burn.gif', ZMQ_BRIDGE: '/demos/zmq_bridge.gif', 'Binance to CV': '/demos/binancetocv.gif', 'mis_take / under_tone / delta': '/demos/undertone.jpg' }
const projectImages = { 'Охота на Снарка': '/media/snark.jpg', 'Белые ночи': '/media/white-nights.jpg', 'Нетерпение': '/media/neterpenije.jpg', 'Необычайные свидания друзей': '/media/vvedensky.png', 'Там, где садятся журавли': '/media/zhuravli.jpg', 'Мусорный ветер': '/media/musorny-veter.jpg', 'Житие Ивана Ерофеича': '/media/ostrovsky.jpg' }
const composerProjects = [
  { title: 'Двойник', info: 'Режиссёр-педагог Екатерина Половцева · ГИТИС', audio: ['/audio/dvojnik.mp3', '/audio/dvojnik-02.mp3'] },
  { title: 'Подросток', info: 'Режиссёр-педагог Вера Камышникова · ГИТИС', audio: ['/audio/podrostok.wav', '/audio/podrostok-02.wav'] },
  { title: 'Небрежный плод моих забав', info: 'Режиссёр Виктория Хомченко', audio: [] },
  { title: 'Маскарад', info: 'Режиссёр Ильяс Гирфанов · Южно-Казахстанский областной драматический театр', audio: ['/audio/maskarad.wav', '/audio/maskarad-02.wav'] },
  { title: 'Поздняя любовь', info: 'Режиссёр Виктория Хомченко · Московский драматический Театр им. Гоголя', audio: ['/audio/pozdnaja-lubov.wav', '/audio/pozdnaja-lubov-02.wav'] },
  { title: 'Субтитры', info: 'Режиссёр Янис Брайловский · радио-спектакль · Россия', audio: ['/audio/subtitry.mp3', '/audio/subtitry-02.mp3'] },
  { title: 'Сахарный ребёнок', info: 'Режиссёр Янис Брайловский · радио-спектакль · Россия', audio: ['/audio/saharny-rebenok.mp3', '/audio/saharny-rebenok-02.wav'] },
  { title: 'Белые ночи', info: 'Челябинский Молодёжный Театр', audio: ['/audio/white-nights.wav', '/audio/white-nights-02.wav'] },
  { title: 'За всё хорошее — смерть', info: 'Режиссёр Никита Огарков · Красноярский Театр Юного Зрителя', audio: ['/audio/za-vsyo-horoshee.wav', '/audio/za-vsyo-horoshee-02.wav'] },
]
const galleryFiles = { snark: Array.from({ length: 12 }, (_, i) => `/media/snark/${String(i + 1).padStart(2, '0')}.jpg`), 'white-nights': Array.from({ length: 7 }, (_, i) => `/media/white-nights/${String(i + 1).padStart(2, '0')}.jpg`), neterpenije: Array.from({ length: 3 }, (_, i) => `/media/neterpenije/${String(i + 1).padStart(2, '0')}.jpg`), vvedensky: ['/media/vvedensky/01.png', '/media/vvedensky/02.jpg', '/media/vvedensky/03.png', '/media/vvedensky/04.png', '/media/vvedensky/05.png', '/media/vvedensky/06.png'], zhuravli: Array.from({ length: 9 }, (_, i) => `/media/zhuravli/${String(i + 1).padStart(2, '0')}.jpg`), 'musorny-veter': ['/media/musorny-veter/01.jpg', '/media/musorny-veter/02.jpg', '/media/musorny-veter/03.jpg', '/media/musorny-veter/04.webp', '/media/musorny-veter/05.webp', '/media/musorny-veter/06.webp'], ostrovsky: Array.from({ length: 6 }, (_, i) => `/media/ostrovsky/${String(i + 1).padStart(2, '0')}.jpg`) }
const projectGallery = { 'Охота на Снарка': galleryFiles.snark, 'Белые ночи': galleryFiles['white-nights'], 'Нетерпение': galleryFiles.neterpenije, 'Необычайные свидания друзей': galleryFiles.vvedensky, 'Там, где садятся журавли': galleryFiles.zhuravli, 'Мусорный ветер': galleryFiles['musorny-veter'], 'Житие Ивана Ерофеича': galleryFiles.ostrovsky }
const assetUrl = (url) => `${import.meta.env.BASE_URL.replace(/\/$/, '')}${url}`

const directorProjects = [
  { title: 'Охота на Снарка', type: 'СПЕКТАКЛЬ', text: 'По поэме Льюиса Кэролла', place: 'РАМТ', date: '23 октября 2026', people: 'Художник: Мика Согоян · Режиссёр по пластике: Вася Серёгин', tone: 'coral' },
  { title: 'Белые ночи', type: 'СПЕКТАКЛЬ', text: 'По повести Фёдора Достоевского', place: 'Челябинский молодёжный театр', date: '10 апреля 2026', people: 'Художник: Алина Варламова · Свет: Анна Короткова', tone: 'blue' },
  { title: 'Нетерпение', type: 'ЛАБОРАТОРИЯ', text: 'По роману Юрия Трифонова', place: 'Санкт-Петербургский ТЮЗ им. Брянцева', date: '25 мая 2026', tone: 'yellow' },
  { title: 'Необычайные свидания друзей', type: 'ЛАБОРАТОРИЯ', text: 'Поэмы, пьесы, письма Александра Введенского', place: 'Новокузнецкий драматический театр', date: '16 августа 2026', tone: 'purple' },
  { title: 'Там, где садятся журавли', type: 'ЛАБОРАТОРИЯ', text: 'По роману Мухаммета Магдеева', place: 'Казанский театр им. Габдуллы Кариева', date: '15 сентября 2026', tone: 'green' },
  { title: 'Мусорный ветер', type: 'УЧЕБНАЯ РАБОТА', text: 'По повестям Андрея Платонова', place: 'ГИТИС', date: '3 июня 2022', tone: 'ink' },
  { title: 'Житие Ивана Ерофеича', type: 'УЧЕБНАЯ РАБОТА', text: 'По повести Александра Островского', place: 'ГИТИС', date: '24 января 2023', tone: 'pink' },
]
const mediaProjects = [
  ['discotemple', 'музыкальный проект', 'саунд как личный портал: шум, клубная энергия, театральная память'], ['DnA / DnB', 'touchdesigner demo', 'аудиовизуальная система для живого изображения'], ['alphafold sonarisation', 'touchdesigner demo', 'перевод научных данных в звуковое пространство'], ['infinite pong ambient', 'touchdesigner · vcv', 'игра как генеративный музыкальный инструмент'], ['paparazzi', 'touchdesigner demo', 'камера, внимание и цифровой след'], ['ZMQ_BRIDGE', 'vst · vcv', 'модуль VCV Rack для обмена данными через ZeroMQ'], ['Binance to CV', 'software experiment', 'курс биткоина превращается в realtime-визуал'], ['mis_take / under_tone / delta', 'audio tools', 'биткрашер, сатуратор и утилита контроля громкости'],
]

function App() {
  const [active, setActive] = useState('director'), [bioOpen, setBioOpen] = useState(true), [clock, setClock] = useState('')
  const [windows, setWindows] = useState({ director: false, composer: false, media: false }), [minimized, setMinimized] = useState({}), [maximized, setMaximized] = useState({}), [zOrder, setZOrder] = useState(['director', 'composer', 'media'])
  const [wallpaperLayers, setWallpaperLayers] = useState([0, 0]), [activeWallpaperLayer, setActiveWallpaperLayer] = useState(0)
  const [minesweeperOpen, setMinesweeperOpen] = useState(false), [startOpen, setStartOpen] = useState(false)
  useEffect(() => { const tick = () => setClock(new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit' }).format(new Date())); tick(); const id = setInterval(tick, 30000); return () => clearInterval(id) }, [])
  const focus = (id) => setZOrder((order) => [...order.filter((item) => item !== id), id])
  const openWindow = (id) => { setWindows((state) => ({ ...state, [id]: true })); setMinimized((state) => ({ ...state, [id]: false })); focus(id); setActive(id) }
  const closeWindow = (id) => setWindows((state) => ({ ...state, [id]: false }))
  const changeWallpaper = () => { const nextLayer = activeWallpaperLayer === 0 ? 1 : 0; const nextIndex = (wallpaperLayers[activeWallpaperLayer] + 1) % wallpapers.length; setWallpaperLayers((layers) => layers.map((value, index) => index === nextLayer ? nextIndex : value)); requestAnimationFrame(() => setActiveWallpaperLayer(nextLayer)) }
  const tabs = useMemo(() => [['director', 'theatre.exe', 'Портфолио режиссера'], ['composer', 'winamp.exe', 'Портфолио композитора'], ['media', 'lab.dll', 'Медиа-арт / software']], [])
  const mobileDevice = typeof navigator !== 'undefined' && /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
  const mobileHost = typeof window !== 'undefined' && window.location.hostname.toLowerCase().startsWith('m.')
  const mobileMode = typeof window !== 'undefined' && (mobileHost || mobileDevice || new URLSearchParams(window.location.search).get('mobile') === '1')
  useEffect(() => { if (mobileDevice && window.location.hostname === 'karim-v.ru') window.location.replace(`https://m.karim-v.ru${window.location.pathname}${window.location.search}${window.location.hash}`) }, [mobileDevice])

  if (mobileMode) return <MobilePortfolio />

  return <main className="desktop"><div className="wallpaper-layer" style={{ backgroundImage: `url(${wallpapers[wallpaperLayers[0]]})`, opacity: activeWallpaperLayer === 0 ? 1 : 0 }} /><div className="wallpaper-layer" style={{ backgroundImage: `url(${wallpapers[wallpaperLayers[1]]})`, opacity: activeWallpaperLayer === 1 ? 1 : 0 }} /><div className="noise" />
    <section className="desktop-icons" aria-label="Разделы портфолио">{tabs.map(([id, file, label]) => <button key={id} className={`desktop-icon ${active === id ? 'selected' : ''}`} onClick={(e) => { e.stopPropagation(); openWindow(id) }}><img className="file-icon image-icon" src={appIcons[id]} alt="" /><span>{file}</span><small>{label}</small></button>)}<button className="desktop-icon" onClick={(e) => { e.stopPropagation(); setBioOpen(true) }}><img className="file-icon image-icon bio" src={bioIcon} alt="" /><span>about.txt</span><small>биография</small></button></section>
    <div className="windows-layer">{tabs.map(([id, file, label]) => windows[id] && !minimized[id] && <Window key={id} id={id} title={file} label={label} z={zOrder.indexOf(id)} maximized={maximized[id]} onFocus={() => focus(id)} onMinimize={() => setMinimized((s) => ({ ...s, [id]: true }))} onMaximize={() => setMaximized((s) => ({ ...s, [id]: !s[id] }))} onClose={() => closeWindow(id)}>{id === 'director' && <Director />}{id === 'composer' && <Composer />}{id === 'media' && <Media />}</Window>)}</div>
    {bioOpen && <Bio onClose={() => setBioOpen(false)} onFocus={() => focus('bio')} />}{minesweeperOpen && <Minesweeper onClose={() => setMinesweeperOpen(false)} />}
    <footer className="taskbar" onClick={(e) => e.stopPropagation()}><button className={`start-button ${startOpen ? 'pressed' : ''}`} onClick={() => setStartOpen((open) => !open)}><span className="windows-logo">▦</span><strong>start</strong></button>{startOpen && <StartMenu onOpen={openWindow} onWallpaper={() => { changeWallpaper(); setStartOpen(false) }} onMinesweeper={() => { setMinesweeperOpen(true); setStartOpen(false) }} onAbout={() => { setBioOpen(true); setStartOpen(false) }} />}<div className="task-buttons">{tabs.map(([id, file]) => windows[id] && <button key={id} className={active === id ? 'task-active' : ''} onClick={() => { setActive(id); setMinimized((s) => ({ ...s, [id]: !s[id] })); focus(id) }}><span>{id === 'director' ? '✦' : id === 'composer' ? '♫' : '◌'}</span>{file}</button>)}{minesweeperOpen && <button className="task-active" onClick={() => setMinesweeperOpen((open) => !open)}>▦ minesweeper</button>}</div><div className="tray"><span className="online-dot" /> available for projects <button className="wallpaper-button" onClick={changeWallpaper}>сменить обои</button><time>{clock}</time></div></footer>
  </main>
}

function StartMenu({ onOpen, onWallpaper, onMinesweeper, onAbout }) { const item = (label, icon, action, note) => <button onClick={action}><span>{icon}</span><div><strong>{label}</strong><small>{note}</small></div></button>; return <div className="start-menu" onClick={(event) => event.stopPropagation()}><div className="start-rail">Windows <span>karim-v.ru</span></div><div className="start-items">{item('about.txt', '▤', onAbout, 'биография и контакты')}{item('theatre.exe', '▣', () => onOpen('director'), 'работы в театре')}{item('winamp.exe', '♫', () => onOpen('composer'), 'портфолио композитора')}{item('lab.dll', '◌', () => onOpen('media'), 'живые системы')}{item('wallpapers.bat', '▧', onWallpaper, 'сменить обои')}{item('mnswpr.bat', '▦', onMinesweeper, 'minesweeper')}</div></div> }

function MobilePortfolio() {
  const [section, setSection] = useState('theatre')
  const [selectedProject, setSelectedProject] = useState(null)
  const [slide, setSlide] = useState(0)
  const [selectedDemo, setSelectedDemo] = useState(null)
  const openProject = (project) => { setSelectedProject(project); setSlide(0) }
  const gallery = selectedProject ? projectGallery[selectedProject.title] || [] : []
  return <main className="mobile-portfolio">
    <header className="mobile-hero"><div className="mobile-brand"><span>KV</span><div><strong>Карим Вахитов</strong><small>theatre · sound · media</small></div></div><a href="https://instagram.com/discotemple" target="_blank" rel="noreferrer">@discotemple ↗</a></header>
    <section className="mobile-intro"><div className="mobile-portrait"><img src={assetUrl('/media/whoami.jpg')} alt="Карим Вахитов" /></div><div><span className="mobile-kicker">личный архив / 2026</span><h1>Режиссёр,<br /><i>композитор</i><br />и художник медиа.</h1><p>Работаю с текстом, телом, звуком и технологиями как с равноправными сценическими материалами.</p></div></section>
    <nav className="mobile-nav" aria-label="Разделы портфолио"><button className={section === 'theatre' ? 'active' : ''} onClick={() => setSection('theatre')}>theatre.exe</button><button className={section === 'sound' ? 'active' : ''} onClick={() => setSection('sound')}>winamp.exe</button><button className={section === 'media' ? 'active' : ''} onClick={() => setSection('media')}>lab.dll</button></nav>
    {section === 'theatre' && <section className="mobile-section"><div className="mobile-section-title"><span>01 / режиссёрский архив</span><h2>Работы<br /><i>в театре.</i></h2><img src={assetUrl('/gif/theatre.gif')} alt="" /></div><div className="mobile-project-list">{directorProjects.map((project) => <button className="mobile-project" key={project.title} onClick={() => openProject(project)}><div className={`mobile-project-image ${project.tone}`}>{projectImages[project.title] && <img src={assetUrl(projectImages[project.title])} alt="" />}<span>{project.type}</span></div><div><h3>{project.title}</h3><p>{project.text}</p><small>{project.place} · {project.date}</small></div><b>↗</b></button>)}</div></section>}
    {section === 'sound' && <section className="mobile-section"><div className="mobile-section-title"><span>02 / original score</span><h2>Портфолио<br /><i>композитора</i></h2><img src={assetUrl('/gif/winamp.gif')} alt="" /></div><p className="mobile-description">Музыка для театра, кино и радио. Два фрагмента из архива для каждого проекта.</p><div className="mobile-track-list">{composerProjects.map((project) => <article className="mobile-track" key={project.title}><div><h3>{project.title}</h3><small>{project.info}</small></div>{project.audio.length ? project.audio.map((src) => <audio key={src} controls preload="metadata" src={assetUrl(src)} />) : <em>demo добавляется</em>}</article>)}</div></section>}
    {section === 'media' && <section className="mobile-section"><div className="mobile-section-title"><span>03 / media lab</span><h2>Живые<br /><i>системы</i></h2><img src={assetUrl('/gif/lab.gif')} alt="" /></div><p className="mobile-description">Медиа-арт, интерактивные объекты, собственные инструменты.</p><div className="mobile-media-list">{mediaProjects.map(([title, type, text]) => <button className="mobile-media" key={title} onClick={() => demoGifs[title] && setSelectedDemo({ title, type, src: demoGifs[title] })}><div className="mobile-media-preview">{demoGifs[title] ? <img src={assetUrl(demoGifs[title])} alt="" /> : <span>TD</span>}</div><div><small>{type}</small><h3>{title}</h3><p>{text}</p>{githubLinks[title] && <a href={githubLinks[title]} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}>GitHub ↗</a>}</div></button>)}</div></section>}
    <footer className="mobile-footer"><span>available for projects</span><a href="mailto:vakhitovkarim2002@gmail.com">contact ↗</a></footer>
    {selectedProject && <div className="mobile-lightbox" onClick={() => setSelectedProject(null)}><div onClick={(event) => event.stopPropagation()}><header><strong>{selectedProject.title}</strong><button onClick={() => setSelectedProject(null)}>×</button></header><div className="mobile-lightbox-image"><button onClick={() => setSlide((slide - 1 + gallery.length) % gallery.length)}>‹</button><img src={assetUrl(gallery[slide])} alt={selectedProject.title} /><button onClick={() => setSlide((slide + 1) % gallery.length)}>›</button></div><small>{slide + 1} / {gallery.length}</small></div></div>}
    {selectedDemo && <div className="mobile-lightbox" onClick={() => setSelectedDemo(null)}><div onClick={(event) => event.stopPropagation()}><header><strong>{selectedDemo.title}</strong><button onClick={() => setSelectedDemo(null)}>×</button></header><img className="mobile-demo-image" src={assetUrl(selectedDemo.src)} alt={`${selectedDemo.title} demo`} /><small>{selectedDemo.type}</small></div></div>}
  </main>
}

function Window({ children, id, title, label, z, maximized, onFocus, onMinimize, onMaximize, onClose }) { return <section className={`window ${maximized ? 'maximized' : ''}`} style={{ zIndex: 10 + z }} onMouseDown={onFocus}><div className="titlebar"><span className="window-glyph">{id === 'director' ? '✦' : id === 'composer' ? '♫' : '◌'}</span><strong>{title}</strong><small>{label}</small><img className="titlebar-gif" src={assetUrl(windowGifs[id])} alt="" /><div className="window-actions"><button onClick={onMinimize}>−</button><button onClick={onMaximize}>□</button><button onClick={onClose}>×</button></div></div><div className="window-menu"><span>File</span><span>Edit</span><span>View</span><span>Help</span><em>karim://portfolio/{id}</em></div>{children}</section> }
function Director() { const [selected, setSelected] = useState(null); const [slide, setSlide] = useState(0); const openGallery = (project) => { setSelected(project); setSlide(0) }; const gallery = selected ? (projectGallery[selected.title] || []) : []; return <><div className="window-content director-content"><div className="section-intro"><div><span className="eyebrow">01 / режиссёрский архив</span><h1 className="vapor-heading">Работы<br /><i>в театре.</i></h1></div><p>Спектакли, лабораторные и учебные работы</p></div><div className="project-grid">{directorProjects.map((project, index) => <article className={`project-card ${project.tone}`} key={project.title} onClick={() => openGallery(project)}><div className="card-art">{projectImages[project.title] && <img className="project-image" src={assetUrl(projectImages[project.title])} alt="" />}<span>0{index + 1}</span><b>{project.type}</b><div className="abstract-shape" /></div><div className="card-body"><h2>{project.title}</h2><p>{project.text}</p><div className="meta"><span>{project.place}</span><time>{project.date}</time></div>{project.people && <small className="people">{project.people}</small>}</div></article>)}</div></div>{selected && <div className="gallery-modal" onClick={() => setSelected(null)}><div className="gallery-window" onClick={(event) => event.stopPropagation()}><div className="gallery-titlebar"><span>{selected.title} — photos</span><button onClick={() => setSelected(null)}>×</button></div><div className="gallery-body"><button className="gallery-arrow" onClick={() => setSlide((slide - 1 + gallery.length) % gallery.length)}>‹</button><img src={assetUrl(gallery[slide])} alt={selected.title} /><button className="gallery-arrow" onClick={() => setSlide((slide + 1) % gallery.length)}>›</button></div><div className="gallery-footer"><span>{String(slide + 1).padStart(2, '0')} / {String(gallery.length).padStart(2, '0')}</span><span>клик по фото — следующий кадр</span></div></div></div>}</> }
function AudioTrack({ src }) { return <audio className="audio-player" controls preload="metadata" src={assetUrl(src)} /> }
function Composer() { return <div className="window-content composer-content"><div className="section-intro"><div><span className="eyebrow">02 / original score</span><h1 className="vapor-heading">Портфолио<br /><i>композитора</i></h1></div><p>Музыка для театра, кино и радио. Для каждого проекта - два фрагмента из архива.</p></div><div className="track-list">{composerProjects.map((project) => <article className="track" key={project.title}><div className="track-info"><strong>{project.title}</strong><small>{project.info}</small></div><div className="track-demos">{project.audio.length ? project.audio.map((src) => <div className="demo-row" key={src}><AudioTrack src={src} /></div>) : <span className="audio-tag">demo добавляется</span>}</div></article>)}</div></div> }
function Media() { const [selected, setSelected] = useState(null); return <><div className="window-content media-content"><div className="section-intro"><div><span className="eyebrow">03 / media lab</span><h1 className="vapor-heading">Живые<br /><i>системы</i></h1></div><p>Медиа-арт, интерактивные объекты, собственные инструменты.</p></div><div className="media-grid">{mediaProjects.map(([title, type, text], i) => <article className="media-card" key={title} onClick={() => setSelected({ title, type, text })}><div className={`media-screen screen-${i % 4} ${demoGifs[title] ? 'has-preview' : ''}`}>{demoGifs[title] ? <img className="media-preview" src={assetUrl(demoGifs[title])} alt={`${title} preview`} /> : <><span>{i < 5 ? 'TD' : 'VCV'}</span><div /><div /></>}</div><div><span className="eyebrow">{type}</span><h2>{title}</h2><p>{text}</p>{githubLinks[title] && <a href={githubLinks[title]} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}>↗ GitHub</a>}<small className="media-hint">{demoGifs[title] ? 'click to open demo' : 'click — demo window'}</small></div></article>)}</div></div>{selected && <div className="demo-modal" onClick={() => setSelected(null)}><div className="demo-window" onClick={(event) => event.stopPropagation()}><div className="gallery-titlebar"><span>{selected.title} — demo.gif</span><button onClick={() => setSelected(null)}>×</button></div>{demoGifs[selected.title] ? <img className="demo-gif" src={assetUrl(demoGifs[selected.title])} alt={`${selected.title} demo`} /> : <div className="demo-empty"><strong>demo.gif</strong><span>GIF пока не добавлен в resources.</span></div>}<div className="gallery-footer"><span>{selected.type}</span>{githubLinks[selected.title] && <a href={githubLinks[selected.title]} target="_blank" rel="noreferrer">↗ открыть GitHub</a>}</div></div></div>}</> }
function Bio({ onClose, onFocus }) { return <aside className="bio-card" onMouseDown={onFocus}><div className="bio-top"><span>about.txt — notepad</span><button onClick={onClose}>×</button></div><div className="bio-inner"><img className="portrait-image" src={assetUrl('/media/whoami.jpg')} alt="Карим Вахитов" /><div><span className="eyebrow">режиссёр · композитор · художник медиа</span><h2>Карим<br />Вахитов</h2></div><div className="bio-details"><span>образование</span><strong>ГИТИС<br />Режиссёрский факультет<br />мастерская С. В. Женовача</strong><span>контакты</span><a href="tel:+79000602712">+7 900 060 27 12</a><a href="mailto:vakhitovkarim2002@gmail.com">vakhitovkarim2002@gmail.com</a><a href="https://t.me/discotemple" target="_blank" rel="noreferrer">telegram: @discotemple</a><a href="https://instagram.com/discotemple" target="_blank" rel="noreferrer">instagram: @discotemple</a></div></div></aside> }

function Minesweeper({ onClose }) {
  const makeBoard = () => { const mines = new Set(); while (mines.size < 10) mines.add(Math.floor(Math.random() * 81)); return Array.from({ length: 81 }, (_, index) => { const row = Math.floor(index / 9); const col = index % 9; const adjacent = []; for (let y = -1; y <= 1; y++) for (let x = -1; x <= 1; x++) { const nextRow = row + y; const nextCol = col + x; if (nextRow >= 0 && nextRow < 9 && nextCol >= 0 && nextCol < 9) adjacent.push(nextRow * 9 + nextCol) } return { mine: mines.has(index), adjacent: adjacent.filter((cell) => mines.has(cell)).length, revealed: false, flagged: false } }) }
  const [board, setBoard] = useState(makeBoard); const [status, setStatus] = useState('ready'); const [seconds, setSeconds] = useState(0); const [flags, setFlags] = useState(0)
  useEffect(() => { if (status !== 'playing') return undefined; const timer = setInterval(() => setSeconds((value) => value + 1), 1000); return () => clearInterval(timer) }, [status])
  const reset = () => { setBoard(makeBoard()); setStatus('ready'); setSeconds(0); setFlags(0) }
  const reveal = (index) => { if (status === 'won' || status === 'lost') return; let next = board.map((cell) => ({ ...cell })); if (next[index].flagged || next[index].revealed) return; if (status === 'ready') setStatus('playing'); if (next[index].mine) { next = next.map((cell) => ({ ...cell, revealed: cell.mine || cell.revealed })); setBoard(next); setStatus('lost'); return } const queue = [index]; while (queue.length) { const current = queue.shift(); if (next[current].revealed || next[current].flagged) continue; next[current].revealed = true; if (next[current].adjacent === 0) { const row = Math.floor(current / 9); const col = current % 9; for (let y = -1; y <= 1; y++) for (let x = -1; x <= 1; x++) { const r = row + y; const c = col + x; const neighbor = r * 9 + c; if (r >= 0 && r < 9 && c >= 0 && c < 9 && !next[neighbor].mine && !next[neighbor].revealed) queue.push(neighbor) } } } const safe = next.filter((cell) => !cell.mine && cell.revealed).length; if (safe === 71) { next = next.map((cell) => cell.mine ? { ...cell, flagged: true } : cell); setStatus('won'); setFlags(10) } setBoard(next) }
  const flag = (event, index) => { event.preventDefault(); if (status === 'won' || status === 'lost' || board[index].revealed) return; const next = board.map((cell) => ({ ...cell })); next[index].flagged = !next[index].flagged; setFlags((value) => value + (next[index].flagged ? 1 : -1)); setBoard(next); if (status === 'ready') setStatus('playing') }
  return <div className="mine-overlay" onClick={onClose}><section className="mine-window" onClick={(event) => event.stopPropagation()}><div className="mine-titlebar"><span>minesweeper.exe</span><button onClick={onClose}>×</button></div><div className="mine-inner"><div className="mine-toolbar"><span>{String(10 - flags).padStart(3, '0')}</span><button className="mine-reset" onClick={reset}>{status === 'lost' ? '☹' : status === 'won' ? '😎' : '☺'}</button><span>{String(seconds).padStart(3, '0')}</span></div><div className="mine-board">{board.map((cell, index) => <button key={index} className={`mine-cell ${cell.revealed ? 'revealed' : ''} ${cell.flagged ? 'flagged' : ''} n${cell.adjacent}`} onClick={(event) => event.shiftKey ? flag(event, index) : reveal(index)} onContextMenu={(event) => flag(event, index)}>{cell.revealed && cell.mine ? '✹' : cell.flagged ? '⚑' : cell.revealed && cell.adjacent ? cell.adjacent : ''}</button>)}</div><div className="mine-help">9 × 9 · 10 mines · Shift+Click to flag</div></div></section></div>
}

export default App
